/*
3474. Lexicographically Smallest Generated String
Solved
Hard
Topics
premium lock icon
Companies
Hint
You are given two strings, str1 and str2, of lengths n and m, respectively.

A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

 

Example 1:

Input: str1 = "TFTF", str2 = "ab"

Output: "ababa"

Explanation:

The table below represents the string "ababa"
Index	T/F	Substring of length m
0	'T'	"ab"
1	'F'	"ba"
2	'T'	"ab"
3	'F'	"ba"
The strings "ababa" and "ababb" can be generated by str1 and str2.

Return "ababa" since it is the lexicographically smaller string.

Example 2:

Input: str1 = "TFTF", str2 = "abc"

Output: ""

Explanation:

No string that satisfies the conditions can be generated.

Example 3:

Input: str1 = "F", str2 = "d"

Output: "a"

 

Constraints:

1 <= n == str1.length <= 104
1 <= m == str2.length <= 500
str1 consists only of 'T' or 'F'.
str2 consists only of lowercase English characters. */

// Solution

class Solution {
    public String generateString(String str1, String str2) {
        int n = str1.length(), m = str2.length(), L = n + m - 1;
        char[] s1 = str1.toCharArray(), s2 = str2.toCharArray();
        
        char[] res = new char[L];
        Arrays.fill(res, '?');

        int[] z = calc_z(s2);
        int last_s2 = -m;

        for (int i = 0; i < n; i++) {
            if (s1[i] != 'T') continue;

            int overlap = Math.max(last_s2 + m - i, 0);

            if (overlap > 0 && z[m - overlap] < overlap) return "";

            for (int j = overlap; j < m; j++) {
                res[i + j] = s2[j];
            }
            last_s2 = i;
        }

        int[] last_free = new int[L];
        int curr = -1;
        for (int i = 0; i < L; i++) {
            if (res[i] == '?') {
                res[i] = 'a';
                curr = i;
            }
            last_free[i] = curr;
        }

        char[] combined = new char[m + L];
        System.arraycopy(s2, 0, combined, 0, m);
        System.arraycopy(res, 0, combined, m, L);
        int[] z_combined = calc_z(combined);

        for (int i = 0; i < n; i++) {
            if (s1[i] != 'F') continue;

            if (z_combined[m + i] >= m) {
                int post_to_change = last_free[i + m - 1];
                if (post_to_change < i) return "";

                res[post_to_change] = 'b';

                i = post_to_change;
            }
        }

        return new String(res);
    }

    private int[] calc_z(char[] s2) {
        int n = s2.length;
        int[] z = new int[n];
        int L = 0, R = 0;

        for (int i = 1; i < n; i++) {
            if (i <= R) {
                z[i] = Math.min(R - i + 1, z[i - L]);
            }

            while (i + z[i] < n && s2[z[i]] == s2[i + z[i]]) {
                L = i;
                R = i + z[i];
                z[i]++;
            }
        }

        if (n > 0) z[0] = n;
        return z;
    }
}
